SELECT CEILING(AVG(SALARY) - AVG(REPLACE(SALARY,'0', ''))) FROM EMPLOYEES;
-- CEILING ROUNDS TO CLOSEST INT, REPLACE TAKES TWO ARGS, CHARACTER WE WANT TO REPLACE & THE CHARACTER WE REPLACE WITH
-- WE ALSO WANT THE AVERAGE SALARY BEFORE & AFTER TRANSFORMATION