SELECT ROUND(SQRT(
    POWER(MAX(LAT_N) - MIN(LAT_N), 2) + 
    POWER(MAX(LONG_W) - MIN(LONG_W), 2))
    ,4) FROM STATION;

-- USE POWER TO TAKE SQUARED VAL OF DIFFERENCE BETWEEN LAT_N'S AND LONG_W'S
-- US SQRT TO TAKE SQUARED ROOT OF THESE COMBINED & ROUND TO 4SF
